### ISSUE TITLE
Upgrade dependency on json4s to newer version

### ISSUE THREAD

**Issue by dsiegmann-ssc** [gphat/datadog-scala#11]
The current json4s dependency version is 3.2.11. This version is not binary compatible with newer versions (tested with 3.4.2). When users of datadog-scala depend on a newer json4s version, it causes this error:

```
java.lang.NoSuchMethodError: org.json4s.FieldSerializer.<init>(Lscala/PartialFunction;Lscala/PartialFunction;Lscala/reflect/Manifest;)V

	at github.gphat.datadog.Client.<init>(Client.scala:20)
```

The `FieldSerializer` class is source compatible, but not binary compatible, due to constructor changes.

Current dependency: https://github.com/json4s/json4s/blob/v3.2.11/core/src/main/scala/org/json4s/FieldSerializer.scala

Newer version: https://github.com/json4s/json4s/blob/v3.4.2/core/src/main/scala/org/json4s/FieldSerializer.scala

Please upgrade to a newer json4s version.

**Comment by gphat** [comment]
Done and new version uploaded. Thanks!
